name: animated_text_effects
description: "A Flutter package with 45 composable text animation effects, sequence widgets, and 4 animated counter widgets."
version: 0.0.4
homepage: https://github.com/alexito8473/animated_text_effects
repository: https://github.com/alexito8473/animated_text_effects
funding:
  - https://github.com/sponsors/alexito8473

environment:
  sdk: ^3.11.5
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
